spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/clubit
<<<<<<< Updated upstream
    password: 8@lNgNl@8
=======
    password: 1234
>>>>>>> Stashed changes
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
thymeleaf:
  cache: false
server:
  port: '8080'
